### ISSUE TITLE
Dimming lights from second generation

### ISSUE THREAD

**Issue by ZiarGames** [ulriklystbaek/smarthouse-ha#2]
Thank you for your code. I've used the build.js, but only get my light functions as simple functions, like this:
```
      - name: "(Fx) Kontor - Taklys(Fx) Kontor - Taklys"
        address: 1182
        slave: 1
        write_type: holding
        scan_interval: 1
        verify:
          input_type: holding
          address: 1182
          state_on: 1
          state_off: 0
```

Which I get in HA, but then I only get on/off. The lights are controlled by:
sh2d500w230
Which is second generation. In the Carlo Gavazzi app I can choose the dimming by using "S2", "S3" and "S4". Do you know if I can get the dimming function into HA?
